apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: multiclusterconfigs.operator.tigera.io
spec:
  group: operator.tigera.io
  names:
    kind: MulticlusterConfig
    listKind: MulticlusterConfigList
    plural: multiclusterconfigs
    singular: multiclusterconfig
  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            clusterManagementType:
              description: 'Valid values for this field are: "standalone", "management",
                "managed"'
              enum:
              - standalone
              - management
              - managed
              type: string
            managementClusterAddr:
              description: Specify where the managed cluster can reach the management
                cluster.
              type: string
            managementClusterPort:
              description: Specify the port that the management cluster is listening
                on.
              format: int64
              type: integer
          type: object
        status:
          properties:
            state:
              description: State provides user-readable status.
              type: string
          type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
