apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tigerastatuses.operator.tigera.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.conditions[?(@.type=="Available")].status
    description: Whether the component running and stable.
    name: Available
    type: string
  - JSONPath: .status.conditions[?(@.type=="Progressing")].status
    description: Whether the component is processing changes.
    name: Progressing
    type: string
  - JSONPath: .status.conditions[?(@.type=="Degraded")].status
    description: Whether the component is degraded.
    name: Degraded
    type: string
  - JSONPath: .status.conditions[?(@.type=="Available")].lastTransitionTime
    description: The time the component's Available status last changed.
    name: Since
    type: date
  group: operator.tigera.io
  names:
    kind: TigeraStatus
    listKind: TigeraStatusList
    plural: tigerastatuses
    singular: tigerastatus
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
