apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: logstorages.operator.tigera.io
spec:
  group: operator.tigera.io
  names:
    kind: LogStorage
    listKind: LogStorageList
    plural: logstorages
    singular: logstorage
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            indices:
              description: Index defines the configuration for the indices in the
                elasticsearch cluster
              properties:
                replicas:
                  description: Replicas defines how many replicas each index will
                    have. See https://www.elastic.co/guide/en/elasticsearch/reference/current/scalability.html
                  format: int64
                  type: integer
              required:
              - replicas
              type: object
            nodes:
              description: Node defines the configuration for the elasticsearch cluster
                nodes. The nodes created will all be of type master, data, and ingest,
                and the number of nodes, where their data is stored, and what the
                resource requirements are configured here
              properties:
                count:
                  description: Count defines the number of nodes that the elasticsearch
                    cluster will have
                  format: int64
                  type: integer
                resourceRequirements:
                  description: ResourceRequirements represents the resource limits
                    and requirements for the elasticsearch cluster (i.e. cpu, size)
                  type: object
              type: object
          type: object
        status:
          properties:
            state:
              description: State indicates the state of the deployment by the LogStorage
                controller
              type: string
          type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
