apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: installations.operator.tigera.io
spec:
  group: operator.tigera.io
  names:
    kind: Installation
    listKind: InstallationList
    plural: installations
    singular: installation
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            cniBinDir:
              description: 'CNIBinDir configures the path on the host where CNI binaries
                will be installed. Default: /opt/cni/bin'
              type: string
            cniNetDir:
              description: 'CNINetDir configures the path on the host where CNI network
                configuration files will be installed. Default: /etc/cni/net.d'
              type: string
            components:
              description: Components specifies the configuration of components.
              properties:
                cni:
                  description: CNI is optional configuration for the CNI component.
                  properties:
                    extraEnv:
                      description: ExtraEnv adds extra environment variables to the
                        CNI container.
                      items:
                        type: object
                      type: array
                    extraVolumeMounts:
                      description: ExtraVolumeMounts configures custom volume mounts
                        to be used by the CNI container.
                      items:
                        type: object
                      type: array
                    extraVolumes:
                      description: ExtraVolumes configures custom volumes to be used
                        by the CNI container.
                      items:
                        type: object
                      type: array
                  type: object
                kubeControllers:
                  description: KubeControllers is optional configuration for the kube-controllers
                    component.
                  properties:
                    extraEnv:
                      description: ExtraEnv adds extra environment variables to the
                        kube-controllers container.
                      items:
                        type: object
                      type: array
                    extraVolumeMounts:
                      description: ExtraVolumeMounts configures custom volume mounts
                        to be used by the kube-controllers container.
                      items:
                        type: object
                      type: array
                    extraVolumes:
                      description: ExtraVolumes configures custom volumes to be used
                        by the kube-controllers container.
                      items:
                        type: object
                      type: array
                    resources:
                      description: Resources configures custom resource requirements
                        on the kube-controllers container.
                      type: object
                    tolerations:
                      description: Tolerations configures custom tolerations on the
                        kube-controllers deployment.
                      items:
                        type: object
                      type: array
                  type: object
                node:
                  description: Node is optional configuration for the node component.
                  properties:
                    extraEnv:
                      description: ExtraEnv adds extra environment variables to the
                        node container.
                      items:
                        type: object
                      type: array
                    extraVolumeMounts:
                      description: ExtraVolumeMounts configures custom volume mounts
                        to be used by the node container.
                      items:
                        type: object
                      type: array
                    extraVolumes:
                      description: ExtraVolumes configures custom volumes to be used
                        by the node daemonset.
                      items:
                        type: object
                      type: array
                    maxUnavailable:
                      anyOf:
                      - type: string
                      - type: integer
                      description: 'MaxUnavailable configures the maximum number of
                        pods that can be unavailable during a rolling update of the
                        node daemonset. Default: 1'
                    resources:
                      description: Resources configures custom resource requirements
                        on the node container.
                      type: object
                    tolerations:
                      description: Tolerations configures custom tolerations on the
                        node daemonset.
                      items:
                        type: object
                      type: array
                  type: object
              type: object
            imagePullSecrets:
              description: ImagePullSecrets is an array of references to Docker registry
                pull secrets.
              items:
                type: object
              type: array
            ipPools:
              description: 'IPPools contains a list of IP pools to use for allocating
                pod IP addresses. For now, a maximum of one IP pool is supported.
                Default: 192.168.0.0/16.'
              items:
                properties:
                  cidr:
                    type: string
                required:
                - cidr
                type: object
              type: array
            registry:
              description: 'Registry is the default Docker registry used for component
                Docker images. Default: docker.io/'
              type: string
            variant:
              description: 'Variant is the product to install - one of Calico or TigeraSecureEnterprise
                Default: Calico'
              type: string
          type: object
        status:
          properties:
            variant:
              description: Variant is the installed product - one of Calico or TigeraSecureEnterprise
              type: string
          type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
